table Dim_StoreFormat
	lineageTag: 15f271c6-ffb3-4c6d-a2fe-19c17d89ae27

	column store_format
		dataType: string
		lineageTag: 25d535e9-8a75-48a3-b4c7-37d2b2855f5a
		summarizeBy: none
		sourceColumn: store_format

		annotation SummarizationSetBy = Automatic

	column StoreFormatKey
		dataType: int64
		formatString: 0
		lineageTag: df0b5fb6-6170-4a6b-a01c-99b7ddae9081
		summarizeBy: none
		sourceColumn: StoreFormatKey

		annotation SummarizationSetBy = Automatic

	partition Dim_StoreFormat = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\Asus\OneDrive - Kumaraguru College of Technology\Desktop\sem 5\Bussines intelligence\Brew_Mini\brewmetrics-bi\brewmetrics_sales.csv"), [Delimiter = ",", Columns = 9, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"sale_id", Int64.Type}, {"date", type date}, {"city", type text}, {"store_format", type text}, {"category", type text}, {"item", type text}, {"quantity", Int64.Type}, {"unit_price", Int64.Type}, {"sales_amount", type number}}, "en-US"),
				  #"Removed other columns" = Table.SelectColumns(#"Changed column type", {"store_format"}),
				  #"Removed duplicates" = Table.Distinct(#"Removed other columns", {"store_format"}),
				  #"Added index" = Table.AddIndexColumn(#"Removed duplicates", "Index", 0, 1, Int64.Type),
				  #"Renamed columns" = Table.RenameColumns(#"Added index", {{"Index", "StoreFormatKey"}})
				in
				  #"Renamed columns"

	annotation PBI_ResultType = Table

